# Generated by Django 5.1.5 on 2025-02-02 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, help_text='Diskon yang ditawarkan oleh pemasok', max_digits=5, null=True)),
                ('stock_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='store.stockorder')),
            ],
        ),
    ]
